FROM python:3.8.3-slim-buster
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update \
&& apt-get -y install g++ libpq-dev gcc unixodbc unixodbc-dev \
&& pip install --upgrade pip \
&& pip install psycopg2

ENTRYPOINT ["python", "read_and_write.py"]