version: '3.5'
services:
  db_srv:
    container_name: db_srv
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      #- POSTGRES_DB=db01
      - PGDATA=/var/lib/postgresql/data
    image: postgres:14.3-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
  py_srv:
    depends_on:
      - db_srv
    container_name: py_srv
    image: python_for_postgre:1
    volumes:
      - .:/usr/src/app


